### ISSUE TITLE
Help/Maintainers wanted

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon-test#12]
The core team of Sinon would like to focus on the core of Sinon, and so we have been moving non-essential functionality out of the core Sinon package into separate packages such as this one. 

This sub-project is currently missing official maintainer, and will not receive as much love as the main Sinon project. If you feel you can help us out, looking through pull requests every now and then, feel free to shout out in the comments section below.

**Comment by fatso83** [comment]
ping  @RobertWHurst  @shaunc @peterjwest 

No obligation, but thought I'd let you know we are looking :-)

**Comment by RobertWHurst** [comment]
I don't want to be solely responsible, but I'm happy to join as a maintainer.

**Comment by mroderick** [comment]
I have added @RobertWHurst as a `collaborator`

**Comment by RobertWHurst** [comment]
Any policies here for collaborators? When should something be merged? Roadmap, etc?

**Comment by mroderick** [comment]
We should probably write something.

"Use good judgement" might be too vague ;)

**Comment by mroderick** [comment]
Typed on a smartphone, sorry for brevity. I'll try to write some guidelines in the next week, and submit a PR for review. I might do this as the first PR into a sinon-shared repo.

**Comment by peterjwest** [comment]
I'd be happy to join as a maintainer.

**Comment by shaunc** [comment]
I'm really very busy until mid June, but could contribute after that.

**Comment by fatso83** [comment]
Check your email, gents ... 

@shaunc: June is approaching ;-)
