### ISSUE TITLE
Move test suite over to using Mocha

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon-test#13]
The main Sinon project has moved the entire test suite over to using Mocha. Using Mochify enables us to run tests easily on Sauce Labs, and people usually know how Mocha works. Buster does work, but it's a little bit harder to debug, and it is not so easy to get running on Sauce Labs so I'd like to see the tests ported. 

One could use the work in the `master` branch of Sinon as a template (search the issues/prs).

**Comment by RobertWHurst** [comment]
I'll start on this.

**Comment by shaunc** [comment]
Any progress? @RobertWHurst -- if you put up a fork with your wip I may have a little time to help out.

**Comment by RobertWHurst** [comment]
I've been working on porting the test framework from the primary sinon repo. Still early on days on it though so I'm not sure if it would be useful. Feel free to give it a go @shaunc.

**Comment by fatso83** [comment]
@shaunc : did you have some time to look at the fork?
