### ISSUE TITLE
Documentation for 3.0.0

### ISSUE THREAD

**Issue by gabegorelick** [sinonjs/sinon-test#160]
3.0.0 was published a few days ago, but there's nothing in [History.md](https://github.com/sinonjs/sinon-test/blob/master/History.md) and [package.json](https://github.com/sinonjs/sinon-test/blob/master/package.json) still lists 2.4.3 as the latest version.

**Comment by fatso83** [comment]
[Seems you are right](https://www.npmjs.com/package/sinon-test)! 

@mroderick : could it be that you forgot the last step of [our release process](https://github.com/sinonjs/sinon-test/blob/master/RELEASE.md#3-push-new-commits-to-github)? Not the first to do so, 😅 .

**Comment by mroderick** [comment]
> @mroderick : could it be that you forgot the last step of [our release process](https://github.com/sinonjs/sinon-test/blob/master/RELEASE.md#3-push-new-commits-to-github)? Not the first to do so, 😅 .

I totally did!

**Comment by gabegorelick** [comment]
Fixed by https://github.com/sinonjs/sinon-test/commit/ade07b742c90e96227b6653f9b3039c27dedd105. I think this can be closed.

Thanks!
