### ISSUE TITLE
TypeScript definitions: `any` type returned for the `this` inside of the test function

### ISSUE THREAD

**Issue by christikaes** [sinonjs/sinon-test#175]
When using sinon-test with TS, it throws an error because the `this` has an implicit any type. To get around this, we used something like this:
```
test(function(this: sinon.SinonSandbox) {...})
```
Would it be possible to update the [type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/sinon-test/index.d.ts#L17) so that it doesn't return an any type?

**Comment by fatso83** [comment]
The Sinon project hsa nothing to do with the type definitions at all. Just file a PR to DefinitelyTyped.
