### ISSUE TITLE
peer dependency with sinon 11?

### ISSUE THREAD

**Issue by anthonyvercolano** [sinonjs/sinon-test#185]
While upgrading my project to sinon 11 I hit the following error:

npm ERR! While resolving: azure-iot-amqp-base@2.4.10
npm ERR! Found: sinon@11.1.2
npm ERR! node_modules/sinon
npm ERR!   dev sinon@"^11.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer sinon@"2.x - 10.x" from sinon-test@3.1.0
npm ERR! node_modules/sinon-test
npm ERR!   dev sinon-test@"^3.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Should there be an update of the peer dependency to 11?

**Comment by fatso83** [comment]
YES :)
