### ISSUE TITLE
Please update your peer deps. Sinon 14 not supported.

### ISSUE THREAD

**Issue by codeninja** [sinonjs/sinon-test#194]
I've run into a problem trying to update  an old repo using Sinon. When updating to Sinon 14 it's revealed that the sinon-test is still locked to version 13.

**Comment by mroderick** [comment]
@fatso83 maybe we can have a CI test that alerts us to this, when we're trying to bump Sinon's major version, without having updated the range in `sinon-test`?

**Comment by fatso83** [comment]
For some reason I managed to close this with the wrong issue reference. Fix in 89a9470.

New version will be published now

--- 

@mroderick Absolutely. Just use [semver](https://www.npmjs.com/package/semver) to check if the current sinon version is covered by `sinon-test`'s peerDependency range?

**Comment by fatso83** [comment]
3.1.4 out with Sinon 14 support
