### ISSUE TITLE
Peer deps update for sinon 15 please

### ISSUE THREAD

**Issue by kf6kjg** [sinonjs/sinon-test#199]
Same basic problem and solution as in #194, this time for Sinon 15

https://github.com/sinonjs/sinon/blob/main/CHANGES.md

**Comment by kf6kjg** [comment]
A possible solution would be to take the same approach as https://github.com/domenic/sinon-chai/blob/master/package.json#L35:

```
"sinon": ">=2.0.0"
```

**Comment by fatso83** [comment]
Yeah, I have been thinking the same for some time. There haven't been any breaking changes since Sinon 2, so should be good for such a tiny bit of functionality.
