### ISSUE TITLE
Travis should run on newer Node versions

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon-test#28]
Cannot update ESLint as newer versions rely on use of `const` and other ES6 features not included in 0.12.

**Comment by mroderick** [comment]
That should be easy enough to fix, since we only run ESLint once: https://github.com/sinonjs/sinon-test/blob/master/.travis.yml#L22

**Comment by fearphage** [comment]
> Cannot update ESLint as newer versions rely on use of const and other ES6 features not included in 0.12.

Double posting now, but I believe we shouldn't be linting the `node_modules` folder. It's not our code. This can be solved by adding `node_modules/` to `.eslintignore`.

**Comment by fearphage** [comment]
Fixed in #27
