### ISSUE TITLE
Deep promises don't get resolved

### ISSUE THREAD

**Issue by vellotis** [sinonjs/sinon-test#31]
Hi

I am glad that sinon-test tries to solve sandboxing for promises with PR #20 (https://github.com/sinonjs/sinon/pull/1128). But there still seems to be a problem with it. If I use deep promises then from some point they don't get resolved and my test reaches timeout. If I stop using `sinon.test` then they will get resolved great.

I don't have a code at the moment that would replicate it. But I am reporting the issue for now and trying to see a way to replicate it without having to provide my enormous [Bookshelf.js](http://bookshelfjs.org) business logic.

**Comment by fatso83** [comment]
OK, that is interesting, but do try to come up with a test case when you got the time.

**Comment by fatso83** [comment]
When something happens deep in your code, then it usually hides a simpler problem by sheer complexity. I will close this until a test case that shows this as a problem surfaces.
