### ISSUE TITLE
sinon.getConfig is deprecated and will be removed from the public API in a future version of sinon.

### ISSUE THREAD

**Issue by tomitrescak** [sinonjs/sinon-test#33]
Hi, am getting error 'sinon.getConfig is deprecated and will be removed from the public API in a future version of sinon.' when using with sinon 2.0.

Do you have an idea how can I use sinon.test environment with sinon 2.0, or how to get rid of this error?

**Comment by fatso83** [comment]
Start with the README, I believe it is covered [precisely there](https://github.com/sinonjs/sinon-test/blob/master/README.md#usage).

---

@sinonjs/sinon-test-maintainers: it would be nice if any of the ones who signed up to do some maintaining of this package in April could contribute at times :-)

**Comment by tomitrescak** [comment]
@fatso83 I have exactly the same configuration as per README, but I see that you have already taken care of it in PR, I'll wait for a release. Thanks

**Comment by fatso83** [comment]
Ah, well then shame on me, but it was sorted out soon enough :-)
