### ISSUE TITLE
No pre-built browser version

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon-test#5]
As [discussed in the sinon project](https://github.com/sinonjs/sinon/issues/1000#issuecomment-192298419), all sinon add-ons/plugins need to be usable in the browser without special handling. So this project needs a build script to produce this browser package.

**Comment by fatso83** [comment]
I am guessing it would be sufficient with one line in the `package.json` file, such as how we do it for [lolex](https://github.com/sinonjs/lolex/blob/master/package.json#L22) (using Browserify)

**Comment by fatso83** [comment]
@sinonjs/sinon-test-maintainers : any chance we'll see progress on this? right now it cannot be used in the browser AFAIK.

**Comment by fatso83** [comment]
ping @RobertWHurst and @shaunc: 
not sure how you intend for people to use this in the browser? bundling it up is a quite simple fix that has been lingering since extracting this package from the main sinon package.

**Comment by RobertWHurst** [comment]
@fatso83 I'm on vacation until next week, but I'll make it happen once I'm back.

**Comment by fearphage** [comment]
What are we thinking here? UMD? IIFE? Multiple packages or just one?

**Comment by fatso83** [comment]
I was just thinking about doing it as simple as possible. It can be used as-is today in node and just bundling it with Browserify should generate a wrapper that will work even if we should split it up or introduce dependencies later on. Size does not matter here.
