### ISSUE TITLE
Sandbox object not accessible on context

### ISSUE THREAD

**Issue by peterjwest** [sinonjs/sinon-test#57]
It would be nice to be able to access the sandbox object from the context object - particularly it would be useful to call `.reset()` on the sandbox for repeated tests.

**Comment by shaunc** [comment]
Hmm... Look at `lib/default-properties.js`. `properties` is a list of properties of the sandbox to inject into the context. I think all you need to do is add copy this properties list and call `configureTest` with the list of default properties expanded with "reset".

Tell me if it works. (They roped me into being a contributor after I submitted a PR for something --- but I'm still still not quite at home with the coding style of the internals.... :))

**Comment by peterjwest** [comment]
I'll have a go, cheers!

**Comment by shaunc** [comment]
[The alternative enhancement would be just to add "reset" to the list of default properties. @fatso83 ?]

**Comment by fatso83** [comment]
I played around with this a bit and found that adding 'reset' is not sufficient, but I also found that you can expose the sandbox object by adding 'sandbox' to the list of properties. Unfortunately, this seems to have exposed a bug, where calling `sandbox.reset` will crash in `fake_server.js` where the responses array has not been initialized.

**Comment by fatso83** [comment]
Fixed the bug causing a crash in sinonjs/sinon#1428. 

Back to the actual issue here, specifying `properties: ['sandbox', 'stub']` on the configure call will expose the sandbox and its reset method:
```javascript
var sinon = require('sinon');
var sinonTest = require('sinon-test');
sinon.test = sinonTest.configureTest(sinon, { 
    properties: ["stub", 'sandbox'] ,
});
var obj = { 'foo' : () => 'foo-val' }
console.log('before stub', obj.foo());

var testSuite = {}

testSuite.myTest = sinon.test( function() {
    var stub = this.stub(obj, 'foo').callsFake( () => 'fake-val' );
    console.log(obj.foo());
    console.log('callCount:',stub.callCount, stub.called); // => 1
    this.sandbox.reset();
    console.log('callCount:',stub.callCount); // => 0
});
testSuite.myTest();
```

**Comment by peterjwest** [comment]
Brilliant, thank you!
