### ISSUE TITLE
Prebuilt Browser version not published ?

### ISSUE THREAD

**Issue by brauliodiez** [sinonjs/sinon-test#58]
Hello,

This come from issue #5, just checked dist version for browser and not available: https://github.com/sinonjs/sinon-test/blob/master/dist/sinon-test.js (404)

Is it something missing on the npm published package? do we have to build it manually? or is there a sinon-test-browser npm package available?

Thanks
  Braulio

**Comment by fatso83** [comment]
Hi, thanks for making us aware of this. Just pushed #62 out to remedy this. Also removed the link to `/dist` in the README to avoid misunderstandings and added a small info line. Will probably push a patch package to NPM within the day.

**Comment by fatso83** [comment]
1.0.2 is out and fixes this:
```
developer@developer-XPS-13-9360:~$ npm i sinon-test
/home/developer
└── sinon-test@1.0.2 
developer@developer-XPS-13-9360:~$ ls -lh node_modules/sinon-test/dist/sinon-test.js 
-rwxrwxr-x 1 developer developer 2,3K mai   11 12:00 node_modules/sinon-test/dist/sinon-test.js
```

**Comment by brauliodiez** [comment]
Will give a try, thanks a lot !
