### ISSUE TITLE
when wrapped test returns promise, restore() shouldn't be called until it resolves

### ISSUE THREAD

**Issue by shaunc** [sinonjs/sinon-test#6]
Problem is that the promise returned by the test calls the spied upon method asyncrhonously - however by then the proxy has been removed and then the chained asyncrhonous check on the spy fails. 

I propose that when return is a promise, then "finally" is used to restore wrapped methods, rather than restoring them syncrhonously. Does this sound right? (can create PR...)

**Comment by fatso83** [comment]
Thanks for the PR in #7, but I am afraid your description is a bit lacking, as I am unable to understand the issue. Of course, this might just be attributed to my lacking command of the English language :smile: 

Could you please post some code that describes what the current issue is and what you are trying to accomplish? Just the normal "Did this, expected foo, got bar" dance.

**Comment by shaunc** [comment]
In mocha (for instance), a test can trigger "asynchronous" mode by returning a promise, rather than accepting a callback:

    it("does something asynchronously", function() {
      return Promise.try(function() { return doSomething(); } ).then(function() {
        return checkSomething();
      });
    });

However, if we wrap this in sinon.test (as it is), the wrapper will immediately restore original functions after the test code returns. This means that the asynchronous code wrapped in the promise will not have had a chance to execute yet, and will not use the spies (or whatever).

I am proposing (implemented in the PR) that if the test returns a promise, the sinon.test wrapper recognize that it is asynchronous, and call the code to restore the wrappers by chaining from the test's promise before returning to the calling test runner (e.g. mocha).

The fork from which the PR is generated works for me, as does the test... except not in "browserify" mode -- it seems not to execute the promises at all no matter what as far as I can tell. I am not familiar with buster/browserify,, however, so don't know how to debug that.

**Comment by fatso83** [comment]
OK, that figures. This has really nothing to do with sinon.test or sandboxing; you are simply [not using Mocha as intended](https://mochajs.org/#asynchronous-code). Testing Promises is not really much different from testing other async functions. This is the usual test of a async function (using ES2015)

    const asyncFn = (fn) => setTimeout(fn, 500);

    it("does something async - callback style", (done) => {
       asyncFn(done);   
    });

This is the same test, just using a promise-based function

    const asyncFn = () => new Promise((resolve, reject) => setTimeout(resolve, 500));

    it("does something async - callback style", (done) => {
       asyncFn().then(done).catch(done);   
    });

**Comment by shaunc** [comment]
Actually, see: https://mochajs.org/#working-with-promises

returning a promise without "done" is alternate to having a "done" callback.

**Comment by shaunc** [comment]
Also e.g. qunit supports returning promise directly -- its not just a mocha idiosyncrasy 

https://api.qunitjs.com/QUnit.test/

**Comment by fatso83** [comment]
Glad to be proven wrong, actually :-) Reopening.
