### ISSUE TITLE
Please publish the latest version to NPM

### ISSUE THREAD

**Issue by zixia** [sinonjs/sinon-test#83]
the latest version of sinon-test on NPM is requiring a peer dependence of `sinon: 2.x-3.x` instead of the master branch: `sinon: 2.x-4.x`.

Please the code from latest master branch to NPM to prevent print warnings, thanks!

**Comment by fatso83** [comment]
Indeed you are right.

```
$ get-npm-file.sh --to-stdout sinon-test@2.1.1 package.json | pick_json -e 'peerDependencies'
{
    "sinon": "2.x - 3.x"
}
```
[get-npm-file](https://github.com/fatso83/dotfiles/tree/master/utils/scripts#get-npm-file)

I'll get this fixed, asap, but I just noticed I have done something stupid: I published version 2.1.1 to NPM, and pushed the tags to GitHub, but I seemed to have forgotten to also push to `master`, meaning `master` doesn't contain [v2.1.1](https://github.com/sinonjs/sinon-test/commits/v2.1.1). Argh.

I seemed to have done `git push --tags`, but not `git push`. I'll try to get it into my head to use `git push --follow-tags`. Will copy over the RELEASE.md from `sinon` to avoid this.

cc @mroderick 
I might have to merge in the tag to remedy this.

**Comment by fatso83** [comment]
```
$ get-npm-file.sh --to-stdout sinon-test@latest package.json | pick_json -e 'peerDependencies'
{
    "sinon": "2.x - 4.x"
}
```

Fixed.

**Comment by zixia** [comment]
Thanks!

**Comment by mantoni** [comment]
@fatso83 That's a very elaborate version of `npm show sinon-test peerDependencies` 😆

**Comment by fatso83** [comment]
Damn. You learn something every day. I just learned that it could output json, after wasting a good afternoon trying to parse it. Thanks 😁
