### ISSUE TITLE
sinon-test not working with QUnit 2.5.0 and promises

### ISSUE THREAD

**Issue by tbiesemann** [sinonjs/sinon-test#90]
Hi,

There is a problem when using sinon-test with QUnit.
In QUnit the test function has a parameter, usually called assert.
QUnit has built in promise support - it is sufficient to return a promise in the test.

sinon-test does not properly pass the promise to the QUnit framework, hence the framework assumes it is a synchronous test and continues, e.g. with afterEach.

This leads to QUnit errors like:
Expected at least one assertion, but none were run - call expect(0) to accept zero assertions.
or 
Error: Assertion occurred after test had finished.

Even worse: as this is a race condition the test might become green while debugging the issue.

Code to reproduce:
```QUnit.module("my test module", {});

sinon.test = sinonTest(sinon, sinon.defaultConfig);

QUnit.test("sinon-test shall return the promise of the test function to the unit test framework", sinon.test(function (assert) {
	var someStub = sinon.stub();
	someStub();
	return Promise.resolve().then(function () {
		sinon.assert.calledOnce(someStub);
	});
}));
```

I will create a pull request for this.

Best,
Thomas

**Comment by tbiesemann** [comment]
#91

**Comment by fatso83** [comment]
2.2.0 is out. Thanks for the help!

**Comment by zixia** [comment]
Awesome, I'm looking forward this feature for a long time!
