### ISSUE TITLE
ES6 Module export

### ISSUE THREAD

**Issue by brettz9** [sinonjs/sinon-test#93]
Now that you kindly implemented https://github.com/sinonjs/sinon/issues/1805 , may I also request a module exposed for `sinon-test` (including `module` on `package.json`)?

It looks like all you will need is an addition to the Rollup config for the "es" format.

While I could make a PR, besides figuring you may have your own ideas on any tests for it, I was also hoping you might first be able to make an npm bump to `sinon` so the dev dependency here (and for other users of versioned sinon) could get the benefit of exclusively using modules.

Thanks so much!

**Comment by fatso83** [comment]
I don't have any new ideas, no. So feel free. Use `npm link` to reference a locally installed Sinon version when testing it out or point to the GitHub version.

We can't cut a new release until fixing sinonjs/sinon#1814

**Comment by mroderick** [comment]
sinonjs/sinon#1814 has been fixed, and `sinon@5.1.0` is on NPM

**Comment by brettz9** [comment]
PR #95 submitted (as well as PR #94 to do some npm/Rollup updating).
